// vue-crash-course/src/components/JobListings.vue
<script setup>
import { RouterLink } from 'vue-router';
import JobListing from './JobListing.vue';
import jobData from '@/jobs.json'
import { ref, defineProps } from 'vue';

defineProps({
    limit: Number,
    showButton: {
        type: Boolean,
        default: false,
    },
})

const jobs = ref(jobData)
console.log(jobs.value)
</script>

<template>
    <section class="bg-blue-50 px-4 py-10">
        <div class="container-xl lg:container m-auto">
            <h2 class="text-3xl font-bold text-green-500 mb-6 text-center"> Browse job</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <JobListing v-for="job in jobs.slice(0, limit || jobs.length)" :key="job.id" :job="job" />
            </div>
        </div>
    </section>

    <section v-if="showButton" class="m-auto max-w-lg my-10 px-6">
        <RouterLink to="/jobs" class="block bg-black text-white text-center py-4 px-6 rounded-xl hover:bg-gray-700">View
            All
            Jobs</RouterLink>
    </section>
</template>

// src/components/JobListings.jsx
import React from 'react'
import jobs from '../jobs.json'
import JobListing from './JobListing'

function JonListings({isHome = false}) {
  console.log(jobs)
  const jobListings = isHome? jobs.slice(0,3) : jobs;

  return (
    <section className="bg-blue-50 px-4 py-10">
      <div className="container-xl lg:container m-auto">
        <h2 className="text-3xl font-bold text-indigo-500 mb-6 text-center">
          { isHome? 'Recent Jobs' : "Browse jobs"}
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {jobListings.map((job) => (
            <JobListing key={job.id} job={job}/>
          ))}

        </div>
      </div>
    </section>)
}

export default JonListings
