// vue-crash-course/src/components/JobListing.vue
<script setup>
import { RouterLink } from 'vue-router';
import { defineProps, ref, computed } from 'vue';

const props = defineProps({
  job: Object
}
)
const showFullDescription = ref(false);

const toggleFullDescription = () => {
  showFullDescription.value = !showFullDescription.value;
}

const truncatedDescription = computed(() => {
  let description = props.job.description
  if (!showFullDescription.value) {
    description = description.substring(0, 90) + "..."
  }
  return description
})
</script>

<template>
  <div class="bg-white rounded-xl shadow-md relative">
    <div class="p-4">
      <div class="mb-6">
        <div class="text-gray-600 my-2">{{ job.type }}</div>
        <h3 class="text-xl font-bold">{{ job.title }}</h3>
      </div>

      <div class="mb-5">
        <div>
          {{ truncatedDescription }}
          <button @click="toggleFullDescription" class="text-green-500 hover:text-green-600 mb-5">{{ showFullDescription ?'Less' :'More' }}</button>
        </div>
      </div>

      <h3 class="text-green-500 mb-2">{{ job.salary }}/ Year</h3>

      <div class="border border-gray-100 mb-5"></div>

      <div class="flex flex-col lg:flex-row justify-between mb-4">
        <div class="text-orange-700 mb-3">
          <i class="pi pi-map-marker text-orange-700"></i>
          {{ job.location }}
        </div>
        <RouterLink :to="'/jobs/' + job.id"
          class="h-[36px] bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded-lg text-center text-sm">
          Read More
        </RouterLink>
      </div>
    </div>
  </div>
</template>

// src/components/JobListing.jsx
import React, { use } from 'react'
import { useState } from 'react'
import { FaMapMarker } from 'react-icons/fa'
import {Link} from 'react-router-dom'

function JobListing({ job }) {
    const [showFullDescription, setShowFullDescription] = useState(false);
    
    let description = job.description;

    if (!showFullDescription) {
        description = description.substring(0,90) + '...';
    }

    return (
        <div className="bg-white rounded-xl shadow-md relative">
            <div className="p-4">
                <div className="mb-6">
                    <div className="text-gray-600 my-2">{job.type}</div>
                    <h3 className="text-xl font-bold">{job.title}</h3>
                </div>

                <div className="mb-5">
                    {description}
                    <button onClick={() => setShowFullDescription((prevState) => !prevState)} 
                    className=" text-indigo-500 mb-5 cursor-pointer hover:text-indigo-600">{showFullDescription ? 'Less': 'More'}</button>
                </div>

                <h3 className="text-indigo-500 mb-2">{job.salary} / Year</h3>

                <div className="border border-gray-100 mb-5"></div>

                <div className="flex flex-col lg:flex-row justify-between mb-4">
                    <div className="text-orange-700 mb-3">
                        <FaMapMarker className='inline text-lg mb-1 mr-1'/>
                        {job.location}
                    </div>
                    <Link
                        to={`/job/${job.id}`}
                        className="h-[36px] bg-indigo-500 hover:bg-indigo-600 text-white px-4 py-2 rounded-lg text-center text-sm"
                    >
                        Read More
                    </Link>
                </div>
            </div>
        </div>
    )
}

export default JobListing
